### ISSUE TITLE
missing include line in search.h

### ISSUE THREAD

**Issue by tissatussa** [visanalexandru/Fortuna#1]
compiling on Linux gave an error .. it says this line should be added to `search.h` :

`#include <memory>`

indeed, then the compilation went well : i get a valid binary and it runs fine in CuteChess.

**Comment by visanalexandru** [comment]
Thank you for submitting this issue! I have added a commit to fix it: https://github.com/visanalexandru/Fortuna/commit/b25fa6eaad6e2c0143e8a2b0cf2a2c95c2ab3f83

**Comment by tissatussa** [comment]
Fortuna seems to play rather well .. it has no version number and i cannot find a rating .. can you elaborate a bit on this ? Do you still improve this engine, or working on a successor ?

**Comment by visanalexandru** [comment]
> Fortuna seems to play rather well .. it has no version number and i cannot find a rating .. can you elaborate a bit on this ? Do you still improve this engine, or working on a successor ?

This is my second attempt at writing a chess engine. This project is just a complete rewrite of my old engine FracTal which had some flaws and was pretty weak. I was planning to submit it to CCRL but I moved on from this project and forgot about it. My estimation of the engine's rating is around 1900 (CCRL rating). I have yet to decide if I will continue to improve this engine or write a third iteration.
